project:
  type: website

website:
  title: "Joyce's Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: coursework.qmd
        text: Coursework

format:
  html:
    theme: minty
    css: styles.css
    toc: true

execute: 
  freeze: auto

