---
title: "Coursework"
editor: visual
---

## University of California, Los Angeles

### Mathematics

- **MATH 164:** Optimization (planned Spring 2024)
- **MATH 151B:** Applied Numerical Methods (planned Spring 2024)
- **MATH 151A:** Applied Numerical Methods (Winter 2024)
- **MATH 134:** Linear and Nonlinear Systems of Differential Equations (Winter 2024)
- **MATH 174E:** Mathematics of Finance for Mathematics/Economics Students (Fall 2023)
- **MATH 131B:** Analysis (Winter 2023)
- **MATH 131A:** Analysis (Spring 2022)
- **MATH 115A:** Linear Algebra (Winter 2022)

### Economics

- **ECON 144:** Economic Forecasting (Winter 2024)
- **ECON 106S:** Competitive Strategy (Spring 2023)
- **ECON 102:** Macroeconomic Theory (Winter 2023)
- **ECON 103:** Econometrics (Summer 2022)
- **ECON 101:** Microeconomic Theory (Spring 2022)

### Statistics

- **STATS 141XP:** Practice of Statistical Consulting (planned Spring 2024)
- **STATS 140XP:** Practice of Statistical Consulting (Winter 2024)
- **STATS 102C:** Introduction to Monte Carlo Methods (Fall 2023)
- **STATS 101C:** Introduction to Statistical Models and Data Mining (Fall 2023)
- **STATS 102B:** Introduction to Computation and Optimization for Statistics (Spring 2023)
- **STATS 101B:** Introduction to Design and Analysis of Experiment (Spring 2023)
- **STATS 102A:** Introduction to Computational Statistics with R (Winter 2023)
- **STATS 101A:** Introduction to Data Analysis and Regression (Winter 2023)
- **STATS 100C:** Linear Models (Fall 2023)
- **MATH 170S:** Introduction to Probability and Statistics: Part 2 Statistics (Spring 2022)
- **MATH 170E:** Introduction to Probability and Statistics: Part 1 Probability (Fall 2021)

### Program in Computing

- **COMPTNG 10C:** Advanced Programming (planned Spring 2024)
- **COMPTNG 16B:** Python with Applications II (Fall 2023)
- **COMPTNG 16A:** Python with Applications I (Winter 2022)
- **COMPTNG 10B:** Intermediate Programming (Fall 2022)
- **COMPTNG 10A:** Introduction to Programming (Spring 2022)

## University of Chicago

- **FINM 25000 91:** Quantitative Portfolio Management and Algorithmic Trading (Summer 2022)